name: Android Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses:  actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Clean Gradle Cache
        run: ./gradlew clean --no-daemon

      - name: Clean and Run Android Lint
        run: ./gradlew clean lint --no-daemon --quiet

      - name: Build APK
        run: ./gradlew assembleRelease --no-daemon --quiet

      - name: Run Unit Tests
        run: ./gradlew test --no-daemon --quiet

      - name: Upload to Firebase (or other deployment platforms)